default: &default
  adapter: postgresql
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>

development:
  <<: *default
  database: ppresent_dev

test:
  <<: *default
  database: ppresent_test

production:
  <<: *default
  database: ppresent_prod
